### ISSUE TITLE
Fedora 34 support

### ISSUE THREAD

**Issue by AsciiWolf** [hiperiondev/sdrangel-Fedora#1]
Please, consider updating your COPR repo to support Fedora 34. Thanks!

**Comment by hiperiondev** [comment]
I haven't updated my notebook yet. I usually do it a couple of months after a new version is released as Fedora tends to have a lot of bugs at startup.
When I do I will start to update it to the new version.
I must also update my tablet since it is on it that I use it regularly.

**Comment by hiperiondev** [comment]
I have recompiled all packages for Fedora 34.

**Comment by AsciiWolf** [comment]
Thanks!
